DBError { Error: { MongoNetworkError: failed to connect to server [157.119.190.112:27017] on first connect [MongoNetworkError: connect ETIMEDOUT 157.119.190.112:27017] at Pool.<anonymous> (d:\Projects\Web Servers\Service\node_modules\mongodb-core\lib\topologies\server.js:564:11) at Pool.emit (events.js:182:13) at Connection.<anonymous> (d:\Projects\Web Servers\Service\node_modules\mongodb-core\lib\connection\pool.js:316:12) at Object.onceWrapper (events.js:273:13) at Connection.emit (events.js:182:13) at Socket.<anonymous> (d:\Projects\Web Servers\Service\node_modules\mongodb-core\lib\connection\connection.js:245:50) at Object.onceWrapper (events.js:273:13) at Socket.emit (events.js:182:13) at emitErrorNT (internal/streams/destroy.js:82:8) at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) name: 'MongoNetworkError', errorLabels: [ 'TransientTransactionError' ], [Symbol(mongoErrorContextSymbol)]: {} }, CreatedTime: 1534307472 }
